// <auto-generated />
namespace MyFollow.DAL.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ownertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ownertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512230843345_owner table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
